env: HMP_compat

env_args:
  map_name: no_map
  env_uuid: hmp00000000000000
  
seed: 9992222
test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
_deprecated_t_max: 2050000